services:
  - type: web
    name: devdeploy
    runtime: node
    rootDir: backend
    buildCommand: cd ../client && npm install && npm run build && cd ../backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
