services:
  - type: web
    name: devdeploy-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: devdeploy_super_secret_jwt_key_2024_change_me
      - key: MONGO_URI
        value: mongodb://127.0.0.1:27017/devdeploy
      - key: CORS_ORIGIN
        value: https://devdeploywebsite.vercel.app
      - key: WORK_DIR
        value: /var/data/workdir
