const fs = require('fs');
const path = require('path');
const { run } = require('./dockerManager');

const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || '/etc/nginx/devdeploy-sites';

/**
 * Ensure NGINX config directory exists.
 */
function ensureDir() {
  if (!fs.existsSync(NGINX_CONF_DIR)) {
    fs.mkdirSync(NGINX_CONF_DIR, { recursive: true });
  }
}

/**
 * Generate and save an NGINX location block config for a deployed project.
 * @param {string} projectName - sanitized project name
 * @param {number} port - host port the container is mapped to
 */
function writeProjectConfig(projectName, port) {
  ensureDir();

  const conf = `# Auto-generated by DevDeploy for project: ${projectName}
location ^~ /${projectName} {
    proxy_pass http://127.0.0.1:${port};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;

    rewrite ^/${projectName}(/.*)$ $1 break;
    rewrite ^/${projectName}$ / break;
}
`;

  const filePath = path.join(NGINX_CONF_DIR, `${projectName}.conf`);
  fs.writeFileSync(filePath, conf, 'utf-8');
  console.log(`[NGINX] Config written: ${filePath}`);
}

/**
 * Remove project NGINX config.
 */
function removeProjectConfig(projectName) {
  const filePath = path.join(NGINX_CONF_DIR, `${projectName}.conf`);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    console.log(`[NGINX] Config removed: ${filePath}`);
  }
}

/**
 * Reload NGINX to pick up config changes.
 */
async function reload() {
  try {
    await run('sudo nginx -t');            // test config first
    await run('sudo systemctl reload nginx');
    console.log('[NGINX] Reloaded successfully.');
  } catch (err) {
    console.error('[NGINX] Reload failed:', err.message);
    throw err;
  }
}

module.exports = { writeProjectConfig, removeProjectConfig, reload };
